### PR TITLE
`morphology/index.md` completed (tasks #3, #4, #5, #7)

### PR DESCRIPTION
**Pull request by pdfkungfoo**
(Never created a GitHub pull request before -- hope it works out)

### CODE REVIEW

**Comment by emcconville** [comment]
Looks like there's a conflict. This can be resolved easily in CLI.

**Comment by pdfkungfoo** [comment]
I tried what's recommended in the CLI help:

```
kp@mb:git.usage-markdown-im6 > git checkout -b KurtPfeifle-master master
Zu neuem Branch 'KurtPfeifle-master' gewechselt

kp@mb:git.usage-markdown-im6 > git checkout -b KurtPfeifle-master master
fatal: Branch 'KurtPfeifle-master' existiert bereits.

kp@mb:git.usage-markdown-im6 > git pull https://github.com/KurtPfeifle/usage-markdown.git master
Von https://github.com/KurtPfeifle/usage-markdown
 * branch            master     -> FETCH_HEAD
Already up-to-date.

kp@mb:git.usage-markdown-im6 > git checkout master
Zu Branch 'master' gewechselt
Ihr Branch ist auf dem selben Stand wie 'origin/master'.

kp@mb:git.usage-markdown-im6 > git merge --no-ff KurtPfeifle-master
Already up-to-date.

kp@mb:git.usage-markdown-im6 > git push origin master
Username for 'https://github.com': KurtPfeifle
Password for 'https://KurtPfeifle@github.com': 
Everything up-to-date
```

No error message -- but still doesn't work.

I'm at a loss right now. Need to start reading up about fine details of Git. (I've never really worked with a _distributed_ Git setup before, where I first forked a master...)

**Comment by emcconville** [comment]
Just resolved, and pushed. There was a line edited twice by both Mark and your self. 

```
commit 9988e512657675302618148de948a374ea6b32af
Merge: 7312735 0c1735d
Author: Eric McConville <emcconville>
Date:   Sat Jul 18 20:36:46 2015 -0500

    Merge branch 'master' of https://github.com/emcconville/usage-markdown

    Conflicts:
        activities---one-sentence-one-line.md
```

Do a `git pull`

**Comment by pdfkungfoo** [comment]
Thanks, Eric.

I still don't understand it yet, but will not be too worried about it
either (for now)   :)

**Pull request merged**
